# Config file used to generate inputs for Beeline using Synthetic networks
global_settings:
  model_dir: "data"
  output_dir: "Synthetic"
  do_simulations: True
  do_post_processing: True
  modeltype: 'hill'

jobs:
  - name: "dyn-BFC"
    model_definition: "dyn-bifurcating-converging.txt"
    model_initial_conditions: "dyn-bifurcating-converging_ics.txt"
    simulation_time: 8
    num_cells: 1000
    do_parallel: True
    nClusters: 2    
        
post_processing:
  GenSamples:
    - sample_size: 1000
      nDatasets: 1

  DimRed:
    - perplexity: 100
