# Config file used to generate inputs for Beeline using Synthetic networks
global_settings:
  model_dir: "data"
  output_dir: "Synthetic"
  do_simulations: True
  do_post_processing: True
  modeltype: 'hill'

jobs:
  - name: "dyn-BFS"
    model_definition: "dyn-bifurcating-simple.txt"
    model_initial_conditions: "dyn-bifurcating-simple_ics.txt"
    simulation_time: 8
    num_cells: 2000
    do_parallel: True
    nClusters: 2    

post_processing:
  GenSamples:
    - sample_size: 500
      nDatasets: 1

  DimRed:
    - perplexity: 100
