# Config file used to generate inputs for Beeline using Synthetic networks
global_settings:
  model_dir: "data"
  output_dir: "Synthetic_10k"
  do_simulations: True
  do_post_processing: True
  modeltype: 'hill'

jobs:
  - name: "dyn-BFStrange"
    model_definition: "dyn-bifurcating-strange.txt"
    model_initial_conditions: "dyn-bifurcating-strange_ics.txt"
    simulation_time: 10
    num_cells: 10000
    do_parallel: True
    nClusters: 2

post_processing:
  GenSamples:
    - sample_size: 10000
      nDatasets: 1
  DimRed:
    - perplexity: 100
