# Config file used to generate inputs for Beeline using Synthetic networks
global_settings:
  model_dir: "data"
  output_dir: "Synthetic"
  do_simulations: True
  do_post_processing: True
  modeltype: 'hill'

jobs:
  - name: "dyn-LL"
    model_definition: "dyn-linear-long.txt"
    model_initial_conditions: "dyn-linear-long_ics.txt"
    simulation_time: 15
    num_cells: 1000
    do_parallel: True
        
post_processing:
  GenSamples:
    - sample_size: 1000
      nDatasets: 10

  DimRed:
    - perplexity: 100
