# Config file used to generate inputs for Beeline using Synthetic networks
global_settings:
  model_dir: "data"
  output_dir: "Synthetic_10k"
  do_simulations: True
  do_post_processing: True
  modeltype: 'hill'

jobs:
  - name: "dyn-SW"
    model_definition: "dyn-switch.txt"
    model_initial_conditions: "dyn-switch_ics.txt"
    simulation_time: 17
    num_cells: 10000
    do_parallel: True
    nClusters: 1

post_processing:
  GenSamples:
    - sample_size: 10000
      nDatasets: 1
  DimRed:
    - perplexity: 100
