# Config file used to generate inputs for Beeline using Synthetic networks
global_settings:
  model_dir: "data"
  output_dir: "Synthetic"
  do_simulations: True
  do_post_processing: True
  modeltype: 'hill'

jobs:
 - name: "dyn-TF"
   model_definition: "dyn-trifurcating.txt"
   model_initial_conditions: "dyn-trifurcating_ics.txt"
   simulation_time: 8
   num_cells: 1000
   do_parallel: True
   nClusters: 3

post_processing:
  GenSamples:
    - sample_size: 1000
      nDatasets: 1
  Dropouts:
    - dropout: False
      drop_cutoff: 0.5
      drop_prob: 0.5
  DimRed:
    - perplexity: 100
